vich_uploader:
    db_driver: orm


    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'



    mappings:
        publication_image:
            uri_prefix: /images/publications
            upload_destination: '%kernel.project_dir%/public/images/publications'
            namer: Vich\UploaderBundle\Naming\UniqidNamer



